server:
  port: 8080

spring:
  application:
    name: post-service

  datasource:
    url: jdbc:postgresql://localhost:5432/social_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    enabled: true
    topics:
      posts: posts

springdoc:
  swagger-ui:
    path: /swagger-ui.html
